project:
  type: website
  output-dir: docs

bibliography: references.bib

website:
  title: "BNFO 420 Capstone"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: overview.qmd
        text: Overview
      - href: research.qmd
        text: Research
      - href: team.qmd
        text: Team
  page-footer:
    left: "BNFO 420 • VCU"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true

execute:
  echo: true
  warning: false
  message: false
