---
title: "The Effect of Omnivorous v. Vegetarian Diet on Gut Microbiota Diversity and the Abundance of TMA-Producing Bacteria in the Human Gut Microbiome"
author: "BNFO 420 Capstone"
---

## Project Summary
Research Question: Do vegetarians and omnivores differ in gut microbiota composition and in the relative abundance of bacterial taxa associated with microbial TMA production?

Hypothesis: Omnivores will have a higher relative abundance of gut microbial taxa associated with microbial TMA production compared to vegetarians.

Our data is a collection of 16s rDNA amplicon of human vegetarian. Dataset is obtained from NCBI, and contains multiple 300-301 long DNA sequences for 57 healthy volunteers based on fecal sample. The raw sequences are a collection of 16s rDNA amplicon of human vegetarian/ominovores. We conducted quality control and generation of ASV once we acquired our data, and then assigned taxonomies to each. This was followed by data normalization, diversity analysis, TMA-producing taxa analysis, and visualization of our data. We intend to deliver a collection of figures including a stacked bar plot (to llustrate the bacterial composition of the different diet groups), a boxplot (to compare the relative abundance of TMA-associated bacteria by diet group), an Alpha diversity plot (showcasing diversity analysis (Shannon index) between diet groups), and a PCoA Plot (showcasing visualization of differences between the diet groups based off of their gut bacteria), as well as a collection of tables including one to summarize the samples, one to illustrate levels of TMA-related bacteria, and one to showcasing statistical test results.

## Project Roadmap 
- [ ] Data acquistion through NCBI
- [ ] Build hypothesis
- [ ] Quality control of sequences and ASV generation
- [ ] Taxonomic assignment
- [ ] Data normalization
- [ ] Diversity analysis
- [ ] TMA-producing taxa analysis
- [ ] Data visualization
- [ ] Execution of deliverables

## Where to find everything
- **Scripts:** `scripts/`
- **Data notes:** `data/README.md`
- **Figures:** `figures/`
- **Citations:** `references.bib`

