---
title: "Overview"
---

## Research Question
Do vegetarians and omnivores differ in gut microbiota composition and in the relative abundance of bacterial taxa associated with microbial TMA production?

## Hypothesis
Omnivores will have a higher relative abundance of gut microbial taxa associated with microbial TMA production compared to vegetarians.

## Dataset
Our data is a collection of 16s rDNA amplicon of human vegetarian. Dataset is obtained from NCBI, and contains multiple 300-301 long DNA sequences for 57 healthy volunteers based on fecal sample. The raw sequences are a collection of 16s rDNA amplicon of human vegetarian/ominovores. We conducted quality control and generation of ASV once we acquired our data, and then assigned taxonomies to each. This was followed by data normalization, diversity analysis, TMA-producing taxa analysis, and visualization of our data. We intend to deliver a collection of figures including a stacked bar plot (to llustrate the bacterial composition of the different diet groups), a boxplot (to compare the relative abundance of TMA-associated bacteria by diet group), an Alpha diversity plot (showcasing diversity analysis (Shannon index) between diet groups), and a PCoA Plot (showcasing visualization of differences between the diet groups based off of their gut bacteria), as well as a collection of tables including one to summarize the samples, one to illustrate levels of TMA-related bacteria, and one to showcasing statistical test results.

License and usage notes: [Downloaded from publicly available dataset on NCBI](https://www.ncbi.nlm.nih.gov/bioproject?LinkName=sra_bioproject&from_uid=5605070)

## Methods Pipeline
- Data acquistion through NCBI
- Build hypothesis
- Quality control of sequences and ASV generation
- Taxonomic assignment
- Data normalization
- Diversity analysis
- TMA-producing taxa analysis
- Data visualization
- Execution of deliverables

## Key Findings
- No significant variation in alpha and beta diversity between the vegetarian and omnivore diet groups
- No significant differences in relative abundance of TMA-associated bacteria and in presence v. absence of TMA-associated bacteria 
- Power analysis indicated that an increase in sample size to n = 171 could show statistical significance in observed trends
- Further study is required to establish a connection between diet and gut microbial composition and diversity, as well as how they influence CVD risk
